// Code generated by "stringer --type MessageType"; DO NOT EDIT.

package main

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ChokeMessage-0]
	_ = x[UnchokeMessage-1]
	_ = x[InterestedMessage-2]
	_ = x[NotInterestedMessage-3]
	_ = x[HaveMessage-4]
	_ = x[BitfieldMessage-5]
	_ = x[RequestMessage-6]
	_ = x[PieceMessage-7]
	_ = x[CancelMessage-8]
	_ = x[PortMessage-9]
}

const _MessageType_name = "ChokeMessageUnchokeMessageInterestedMessageNotInterestedMessageHaveMessageBitfieldMessageRequestMessagePieceMessageCancelMessagePortMessage"

var _MessageType_index = [...]uint8{0, 12, 26, 43, 63, 74, 89, 103, 115, 128, 139}

func (i MessageType) String() string {
	if i >= MessageType(len(_MessageType_index)-1) {
		return "MessageType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _MessageType_name[_MessageType_index[i]:_MessageType_index[i+1]]
}
